BUSI:
  Dataset Cohort: Dataset_Breast.json
  Dataset ID: breast
  Dataset Path: Dataset_Breast
  Dataset Sequence: 0
TUSI:
  Dataset Cohort: Dataset_Thyroid.json
  Dataset ID: thyroid
  Dataset Path: Dataset_Thyroid
  Dataset Sequence: 1
METADATA:
  Dataset Cohort: Dataset_METADATA/Dataset_METADATA.json
  Dataset ID: metadata_breast
  Dataset Path: Dataset_METADATA
  Dataset Sequence: 2
